name: Kotlin Multiplatform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Android build job
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android
        run: ./gradlew assembleRelease --info

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: composeApp/build/outputs/apk/release/*.apk

  # iOS build job
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install CocoaPods (if needed)
        run: |
          if [ -f iosApp/Podfile ]; then
            echo "Installing CocoaPods dependencies..."
            pod install --project-directory=iosApp
          else
            echo "No Podfile found. Skipping CocoaPods installation."
          fi

      - name: Build iOS app
        run: |
          if [ -d iosApp/iosApp.xcworkspace ]; then
            echo "Building with .xcworkspace..."
            xcodebuild -allowProvisioningUpdates \
              -workspace iosApp/iosApp.xcworkspace \
              -scheme iosApp \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              build CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY="" \
              DEVELOPMENT_TEAM=""
          else
            echo "Building with .xcodeproj..."
            xcodebuild -allowProvisioningUpdates \
              -project iosApp/iosApp.xcodeproj \
              -scheme iosApp \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              build CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY="" \
              DEVELOPMENT_TEAM=""
          fi

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: |
            iosApp/build/Release-iphoneos/*.app

  # Desktop build job
  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Desktop
        run: ./gradlew desktopJar

      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar
          path: composeApp/build/libs/*.jar

  # Web build job
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Web
        run: ./gradlew wasmJsBrowserDistribution

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: composeApp/build/dist/wasmJs/productionExecutable

  # Generate artifact links
  generate-artifact-links:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-desktop, build-web]
    steps:
      - name: Generate Artifact Table
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{ github.run_id }}
          REPO=${{ github.repository }}
          ARTIFACTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts")
          echo "| Platform | Artifact | Link |" > artifacts.md
          echo "|----------|----------|------|" >> artifacts.md
          echo "$ARTIFACTS" | jq -r '.artifacts[] | "\(.name) \(.archive_download_url)"' | while read -r line; do
            NAME=$(echo "$line" | cut -d ' ' -f1)
            URL=$(echo "$line" | cut -d ' ' -f2)
            echo "| $NAME | Artifact | [Download]($URL) |" >> artifacts.md
          done
          cp artifacts.md README.md
